using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ARS.Common.Enums
{
    public enum Country
    {
        Afghanistan
        , Albania
        , Algeria
        , Andorra
        , Angola
        , AntiguAandBarbuda
        , Argentina
        , Armenia
        , Australia
        , Austria
        , Azerbaijan
        , TheBahamas
        , Bahrain
        , Bangladesh
        , Barbados
        , Belarus
        , Belgium
        , Belize
        , Benin
        , Bhutan
        , Bolivia
        , BosniaAndHerzegovina
        , Botswana
        , Brazil
        , Brunei
        , Bulgaria
        , BurkinaFaso
        , Burundi
        , CaboVerde
        , Cambodia
        , Cameroon
        , Canada
        , CentralAfricanRepublic
        , Chad
        , Chile
        , China
        , Colombia
        , Comoros
        , DemocraticRepublicOfCongo
        , CostaRica
        , CôtedIvoire
        , Croatia
        , Cuba
        , Cyprus
        , CzechRepublic
        , Denmark
        , Djibouti
        , Dominica
        , DominicanRepublic
        , Ecuador
        , Egypt
        , ElSalvador
        , EquatorialGuinea
        , Eritrea
        , Estonia
        , Eswatini
        , Ethiopia
        , Fiji
        , Finland
        , France
        , Gabon
        , Gambia
        , Georgia
        , Germany
        , Ghana
        , Greece
        , Grenada
        , Guatemala
        , Guinea
        , GuineaBissau
        , Guyana
        , Haiti
        , Honduras
        , Hungary
        , Iceland
        , India
        , Indonesia
        , Iran
        , Iraq
        , Ireland
        , Israel
        , Italy
        , Jamaica
        , Japan
        , Jordan
        , Kazakhstan
        , Kenya
        , Kiribati
        , NorthKorea
        , SouthKorea
        , Kosovo
        , Kuwait
        , Kyrgyzstan
        , Laos
        , Latvia
        , Lebanon
        , Lesotho
        , Liberia
        , Libya
        , Liechtenstein
        , Lithuania
        , Luxembourg
        , Madagascar
        , Malawi
        , Malaysia
        , Maldives
        , Mali
        , Malta
        , MarshallIslands
        , Mauritania
        , Mauritius
        , Mexico
        , Moldova
        , Monaco
        , Mongolia
        , Montenegro
        , Morocco
        , Mozambique
        , Burma
        , Namibia
        , Nauru
        , Nepal
        , Netherlands
        , NewZealand
        , Nicaragua
        , Niger
        , Nigeria
        , NorthMacedonia
        , Norway
        , Oman
        , Pakistan
        , Palau
        , Panama
        , PapuaNewGuinea
        , Paraguay
        , Peru
        , Philippines
        , Poland
        , Portugal
        , Qatar
        , Romania
        , Russia
        , Rwanda
        , Samoa
        , SanMarino
        , SaudiArabia
        , Senegal
        , Serbia
        , Seychelles
        , SierraLeone
        , Singapore
        , Slovakia
        , Slovenia
        , SolomonIslands
        , Somalia
        , SouthAfrica
        , Spain
        , SriLanka
        , Sudan
        , Suriname
        , Sweden
        , Switzerland
        , Syria
        , Taiwan
        , Tajikistan
        , Tanzania
        , Thailand
        , Togo
        , Tonga
        , TrinidadAandTobago
        , Tunisia
        , Turkey
        , Turkmenistan
        , Tuvalu
        , Uganda
        , Ukraine
        , UnitedArabEmirates
        , UnitedKingdom
        , UnitedStates
        , Uruguay
        , Uzbekistan
        , Vanuatu
        , VaticanCity
        , Venezuela
        , Vietnam
        , Yemen
        , Zambia
        , Zimbabwe
    }
}
